# This user is for the comment process
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: find-new
  namespace: ao3
spec:
  rabbitmqClusterReference:
    name: message-broker
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: find-new-permission
  namespace: ao3
spec:
  vhost: "/"
  userReference:
    name: "find-new"  # refers to name of User resource
  permissions:
    write: ".*"
    configure: ""
    read: ".*"
  rabbitmqClusterReference:
    name: message-broker
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: find-new
  namespace: ao3
  labels:
    app: find-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: find-new
  template:
    metadata:
      labels:
        app: find-new
    spec:
      containers:
        - name: find-new
          image: registry.danya02.ru/danya02/ao3/find-new:latest
          imagePullPolicy: Always
          env:
            - name: RUST_LOG
              value: debug
            - name: AMQP_SERVER
              value: message-broker
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: find-new-user-credentials
                  key: username
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: find-new-user-credentials
                  key: password
            - name: PROXY_URL
              value: socks5://shadowsocks-client-service:1080